name: Deploy All Branches and Tags to Pages

on:
  workflow_dispatch: # Manual trigger for redeployment of all branches and tags

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-all:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches and tags

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Create Deployment Directory
        run: mkdir -p public  # Initialize a public directory for deployments

      - name: Deploy Each Branch
        run: |
          # Loop through all branches and deploy each one
          bash -c 'for branch in $(git branch -r | grep -v '\->' | grep -v 'HEAD' | sed 's/origin\///'); do
            echo "Deploying branch: $branch"
            git checkout $branch
            mkdir -p "public/$branch"
            # Copy all contents except the 'public' directory itself
            shopt -s extglob
            cp -r !(public) "public/$branch"
          done'

      - name: Deploy Each Tag
        run: |
          # Loop through all tags and deploy each one
          bash -c 'for tag in $(git tag); do
            echo "Deploying tag: $tag"
            git checkout $tag
            mkdir -p "public/$tag"
            # Copy all contents except the 'public' directory itself
            shopt -s extglob
            cp -r !(public) "public/$tag"
          done'

      - name: Generate Index.html
        run: |
          INDEX_PATH="public/index.html"
          echo "<html><body><h1>Deployed Branches and Tags</h1><ul>" > $INDEX_PATH
          
          # Add each branch and tag to the index
          for dir in $(ls -d public/*/); do
            DIR_NAME=$(basename "$dir")
            echo "<li><a href='/firstspirit-snap-extension/${DIR_NAME}/'>${DIR_NAME}</a></li>" >> $INDEX_PATH
          done
          
          echo "</ul></body></html>" >> $INDEX_PATH

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
